[build]
  command = "bash build.sh"
  publish = "dist/client"
  functions = "dist/functions"

[dev]
  command = "npm run dev"
  port = 5000
  publish = "dist/client"

[[redirects]]
  from = "/"
  to = "/splash.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200